import { useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2, Fingerprint, ScanLine, ShieldCheck, FlaskConical, X, FileText } from 'lucide-react'
import { calculateScore, effectiveStatus, runCompliance } from './lib/compliance'
import type { Inspection } from './types'

export function CommandHome({ inspections, openInspection, startInspection, openDemo }: {
  inspections: Inspection[]; openInspection: (id: string) => void; startInspection: () => void; openDemo: () => void
}) {
  const live = inspections.filter((record) => record.source === 'created')
  const queue = [...live].filter((record) => record.status !== 'Compliant').sort((a, b) => a.score - b.score)
  return <div className="command-home">
    <div className="welcome-line"><span>DOTCOM / INSPECTION WORKSPACE</span><span className="version-tag">ROUND 02</span></div>
    <section className="command-hero">
      <div className="command-copy"><span className="section-kicker"><ShieldCheck size={17} /> EVERY DECLARATION COUNTS</span><h2>A clearer picture.<br /><em>A fairer marketplace.</em></h2><p>Read a package. Understand the findings. Connect the same product across inspections.</p><div className="hero-buttons"><button className="primary-button" onClick={startInspection}><ScanLine size={19} /> Scan a product <ArrowRight size={18} /></button><button className="text-button" onClick={openDemo}>Explore the guided demo <ArrowRight size={16} /></button></div><div className="hero-footnote"><span><CheckCircle2 size={14} /> Photos processed in your browser</span><span>12 screening checks</span></div></div>
      <div className="hero-specimen" aria-label="Illustrative sample inspection"><div className="specimen-top"><span>SAMPLE EVIDENCE</span><ScanLine size={20} /></div><img src="/demo-aurelia-back.svg" alt="Sample HydraGlow back label" /><div className="specimen-callout"><Fingerprint size={24} /><div><strong>One product. A connected history.</strong><span>Compare the declarations behind the label.</span></div></div></div>
    </section>
    <div className="workspace-stats"><div><strong>{live.length.toString().padStart(2, '0')}</strong><span>Your saved inspections</span></div><div><strong>{queue.length.toString().padStart(2, '0')}</strong><span>Awaiting attention</span></div><div><strong>{live.reduce((total, record) => total + record.images.length, 0).toString().padStart(2, '0')}</strong><span>Evidence photographs</span></div><div className="storage-caption"><ShieldCheck size={22} /><span>Saved on this device<br /><small>Original photos stay with the report</small></span></div></div>
    <section className="workflow-strip"><div><span>01</span><strong>Capture</strong><p>Upload the label surfaces.</p></div><ArrowRight /><div><span>02</span><strong>Verify</strong><p>Review the text and evidence.</p></div><ArrowRight /><div><span>03</span><strong>Connect</strong><p>Reveal changes with Product DNA.</p></div></section>
    <section className="panel attention-panel"><div className="panel-header"><div><h3>Your inspection queue</h3><p>Saved scans that need verification, ordered by lowest screening score.</p></div><span className="truth-chip live">YOUR RECORDS</span></div>{queue.length ? queue.slice(0, 5).map((record) => <button className="queue-row" key={record.id} onClick={() => openInspection(record.id)}><span className="queue-score">{record.score}</span><div><strong>{record.details.name}</strong><small>{record.details.brand} · {record.details.location}</small></div><span>{record.findings.filter((finding) => effectiveStatus(finding) === 'violation').length} flags</span><ArrowRight size={18} /></button>) : <div className="queue-empty"><CheckCircle2 size={25} /><div><strong>{live.length ? 'No scans awaiting attention' : 'Your first inspection starts here'}</strong><p>{live.length ? 'Open Past scans to revisit your saved records.' : 'Scan a package to build your own evidence repository. Sample cases remain separate.'}</p></div><button className="secondary-button" onClick={startInspection}>Start a scan <ArrowRight size={16} /></button></div>}</section>
    <div className="home-caption">NiyamDrishti supports officer review. The screening score is a prototype indicator, not a legal certification.</div>
  </div>
}

export function CorrectionLab({ inspection }: { inspection: Inspection }) {
  const [open, setOpen] = useState(false)
  const [draft, setDraft] = useState(inspection.ocrText)
  const [evaluated, setEvaluated] = useState<string | null>(null)
  const baseline = useMemo(() => runCompliance(inspection.details, inspection.ocrText), [inspection])
  const findings = useMemo(() => evaluated === null ? null : runCompliance(inspection.details, evaluated), [inspection, evaluated])
  const changed = findings?.filter((finding) => baseline.find((item) => item.field === finding.field)?.status !== finding.status) ?? []
  return <section className="correction-lab no-print"><button className="lab-toggle" onClick={() => setOpen(!open)} aria-expanded={open}><span className="lab-icon"><FlaskConical size={23} /></span><span><strong>What if the label were corrected?</strong><small>Test proposed text and see which findings change.</small></span>{open ? <X size={20} /> : <ArrowRight size={20} />}</button>{open && <div className="lab-body"><p className="lab-notice">Simulation only. This does not alter the inspection, prove a package was corrected, or carry over officer overrides.</p><label htmlFor="correction-text">Proposed label declarations</label><textarea id="correction-text" value={draft} onChange={(event) => { setDraft(event.target.value); setEvaluated(null) }} /><div className="lab-actions"><button className="secondary-button" onClick={() => { setDraft(inspection.ocrText); setEvaluated(null) }}>Reset to captured text</button><button className="primary-button" disabled={!draft.trim()} onClick={() => setEvaluated(draft)}>Test correction <ArrowRight size={16} /></button></div>{findings && <div className="simulation-result" role="status"><div className="simulation-score"><FileText size={22} /><span>Text-only screening score</span><strong>{calculateScore(baseline)} <ArrowRight size={20} /> {calculateScore(findings)}</strong></div><h4>{changed.length} finding{changed.length !== 1 ? 's' : ''} changed</h4>{changed.length ? changed.map((finding) => <div className="simulation-change" key={finding.field}><strong>{finding.title}</strong><span>{baseline.find((item) => item.field === finding.field)?.status} → {finding.status}</span><small>{finding.observed}</small></div>) : <p>No rule outcomes changed. Check whether the proposed text addresses the flagged declaration.</p>}<p>Re-scan the actual corrected package to create evidence of resolution.</p></div>}</div>}</section>
}
